spring:
    application:
        name: itau

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    datadog:
        metrics:
            export:
                enabled: true
                api-key: ${DD_API_KEY}
                step: 10s
                    